apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deployment-dev.yaml
- path: service-dev.yaml

generatorOptions:
  labels:
    fruit: apple

configMapGenerator:
- name: index-dev-html-configmap-7b58b6dj6d
  behavior: create
  files:
  - index-dev.html
